function y = helmholtzmultipole(a,c,k,r)
    P = (length(a)-1) / 2;
    arr = arrayfun( ...
        @(j) a(j+P+1) * besselj(j, k*vecnorm(r - c)) .* exp(1i*j*atan2(r(2,:) - c(2), r(1,:) - c(1))), ...
        -P:P, ...
        'UniformOutput', false ...
        );
    y = sum(cat(3, arr{:}),3);
end