# based on Dan Fortunato's ultra SEM repo

name: chunkie tests
on: [push]
jobs:
  ultraSEM-test:
    name: do chunkie tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive	
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0
      - name: Install FMMLIB
        run: cd chunkie/fmm2d; make matlab
      - name: Run commands
        uses: matlab-actions/run-command@v0
        with:
          command: cd('./devtools/test'); res = runtests; assert(all([res.Passed]))